# Generated by Django 5.2.5 on 2025-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONING", "Provisioning"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("ERROR", "Error"),
                        ],
                        default="PROVISIONING",
                        max_length=20,
                    ),
                ),
                ("render_service_ids", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
