# Generated by Django 4.2.23 on 2025-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="custom_plugin_repo",
            field=models.URLField(
                blank=True, help_text="Git repository URL for custom plugins", null=True
            ),
        ),
    ]
