# Generated by Django 4.2.23 on 2025-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_custom_plugin_repo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="tenants_ten_status_e7eaee_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["created_at"], name="tenants_ten_created_99c6ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["name"], name="tenants_ten_name_87437c_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["status", "created_at"], name="tenants_ten_status_3cf878_idx"
            ),
        ),
    ]
